module RedmineTimeAnalytics
  # Redmine Time Analytics Plugin Library
end

require_relative 'redmine_time_analytics/working_days_calculator'
require_relative 'redmine_time_analytics/leave_email_parser'
require_relative 'redmine_time_analytics/simple_leave_email_parser'
require_relative 'redmine_time_analytics/ai_leave_extractor'
require_relative 'redmine_time_analytics/hybrid_leave_extractor'
require_relative 'redmine_time_analytics/leave_providers/base_provider'
require_relative 'redmine_time_analytics/leave_providers/gmail_base_provider'
require_relative 'redmine_time_analytics/leave_providers/gmail_oauth_provider'
require_relative 'redmine_time_analytics/leave_fetcher_factory'
require_relative 'redmine_time_analytics/gmail_leave_fetcher'
require_relative 'redmine_time_analytics/leave_sync_service'
require_relative 'redmine_time_analytics/missing_time_email_template'
require_relative 'redmine_time_analytics/missing_time_notification_service'
require_relative 'redmine_time_analytics/missing_time_scheduler'
require_relative 'redmine_time_analytics/external_time_cache_scheduler'
require_relative 'redmine_time_analytics/time_entry_patch'
require_relative 'redmine_time_analytics/issue_patch'
require_relative 'redmine_time_analytics/time_entry_query_patch'
require_relative 'redmine_time_analytics/issue_query_patch'
require_relative 'redmine_time_analytics/time_report_patch'
